openapi: '3.0.2'
info:
  version: '1.0'
  title: 'Course Work Services API'
  description: Software Architecture Accommodation service API
servers:
  - url: http://localhost:8080
    description: Web server
paths:
  /accommodation/search:
    get:
      