openapi: '3.0.2'
info:
  version: '1.0'
  title: 'Course Work Services API'
  description: Software Architecture Accommodation service API
servers:
  - url: http://localhost:8081
    description: Web server
paths:
  /accommodation/create:
    post:
      tags:
        - accommodation_service
      summary: Create accommodation
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                deadline:
                  type: string
                  example: '2024-04-06T16:00:00Z'
                description:
                  type: string
                  example: '{{$randomCatchPhrase}}'
                id:
                  type: string
                  example: '{{$randomInt}}'
                name:
                  type: string
                  example: '{{$randomBsBuzz}}'
                price:
                  type: string
                  example: '{{$randomInt}}'
      responses:
        '200':
          description: ''
      security:
        - jwtBearerAuth: []
  /accommodation:
    get:
      summary: Get accommodation
      parameters:
        - name: id
          in: query
          schema:
            type: string
            example: '2'
      responses:
        '200':
          description: ''
      security:
        - jwtBearerAuth: []
    delete:
      tags:
        - accommodation_service
      summary: accommodation delete
      description: accommodation delete
      operationId: accommodationDelete
      parameters:
        - name: id
          in: query
          schema:
            type: string
            example: '671'
      responses:
        '200':
          description: ''
      security:
        - jwtBearerAuth: []
  /accommodation/search:
    get:
      summary: Search accommodation 
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: Sample Accommodation 1
      responses:
        '200':
          description: ''
      security:
        - jwtBearerAuth: []
components:
  schemas:
    accommodation_id:
      description: Accommodation id
      type: integer
    accommodations:
      type: array
      items:
        $ref: '#/components/schemas/accommodation'
    accommodation:
      type: object
      properties:
        accommodation_id:
          type: integer
        accommodation_name:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Error message
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []
